permissions:
  contents: write

name: Update Design Tokens

on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update JSON file
        run: |
          echo '${{ github.event.client_payload.tokens }}' > design-tokens.json

      - name: Commit and push
        run: |
          git config --local user.email "arihan.awasthi@viamagus.com"
          git config --local user.name "arihanVM"
          git add design-tokens.json
          git commit -m "${{ github.event.client_payload.commitMessage }}"
          git push
